# Generated by Django 2.2.5 on 2019-12-27 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='a_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('xml', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=1, unique=True)),
                ('member_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='myUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limits', models.IntegerField(choices=[(0, '普通用户'), (1, '用户组长')], default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='a_text',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.group'),
        ),
        migrations.AddField(
            model_name='a_text',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.myUser'),
        ),
    ]
