# Generated by Django 2.2.5 on 2019-12-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_auto_20191227_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='index',
        ),
        migrations.AddField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='annotation', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='limits',
            field=models.IntegerField(choices=[(1, '用户组长'), (0, '普通用户')], default=0),
        ),
    ]
