# Generated by Django 3.0.1 on 2019-12-29 16:56

import annotation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_auto_20191228_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.FileField(upload_to=annotation.models.text_path)),
                ('index', models.IntegerField(default=0)),
                ('limit', models.IntegerField(default=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.group')),
            ],
        ),
    ]
