# Generated by Django 3.0.1 on 2019-12-30 05:29

import annotation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0004_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_text',
            name='xml',
            field=models.FileField(upload_to=annotation.models.xml_path),
        ),
    ]
